-- Explore all countries our customer come from.
SELECT DISTINCT country FROM gold.dim_customers

-- Explore all product categiries "The Major Divisions"
SELECT DISTINCT category, subcategory, product_name FROM gold.dim_products
ORDER BY 1,2,3

-- Explore date ranges
-- Find the date of the first and last order
-- How many years of sales are available 
SELECT
	MIN(order_date) As first_order_date,
	MAX(order_date) As last_order_date,
	DATEDIFF(YEAR, MIN(order_date), MAX(order_date)) AS order_range_years,
	DATEDIFF(MONTH, MIN(order_date), MAX(order_date)) AS order_range_month
FROM gold.fact_sales

-- Find the youngest and oldest customer
SELECT
	MIN(birthdate) AS  oldest_birtdate,
	DATEDIFF(YEAR, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_birthdate,
	DATEDIFF(YEAR, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers

-- ** Measures **
-- Find the total sales
SELECT SUM(sales_amount) AS total_sales FROM gold.fact_sales

-- Find how many items are sold
SELECT SUM(quantity) AS total_quantity FROM gold.fact_sales

-- Find the average selling price
SELECT AVG(price) AS avg_price FROM gold.fact_sales

-- Find the total number of Orders
SELECT COUNT(order_number) AS total_sales FROM gold.fact_sales
SELECT COUNT(DISTINCT order_number) AS total_orders FROM gold.fact_sales

-- Find the total number of products
SELECT COUNT(product_key) AS total_products FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) AS total_products FROM gold.dim_products

-- Find the total number of customers
SELECT COUNT(DISTINCT customer_key) AS total_customers FROM gold.dim_customers

-- Find the total number of customers that has placed an order.
SELECT COUNT(DISTINCT customer_key) AS total_customers_placed_order FROM gold.fact_sales

-- Genrate Report that shows all key metrics of the business.
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Orders' AS measure_name, COUNT(DISTINCT order_number)  AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Products' AS measure_name, COUNT(DISTINCT product_key) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total No. Customers' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total No. Customers placed Orders' AS measure_name, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales

-- Find total customers by countries
SELECT
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find total products by category 
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
	category,
	AVG(cost) AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC;

-- What is the total revenue generated for each category?
SELECT 
	p.category,
	SUM(s.sales_amount) AS total_revenue
FROM gold.dim_products p
JOIN gold.fact_sales s
ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;

-- Find total revenue is generated by each customer
SELECT
	c.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS total_revenue 
FROM gold.dim_customers c
JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?	
SELECT
	c.country,
	SUM(s.quantity) as total_sold_items
FROM gold.dim_customers c
JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY country
ORDER BY total_sold_items DESC;

-- Which 5 products generate the highest revenue?
SELECT
	product_name,
	total_revenue
FROM (
	SELECT 
		p.product_name,
		SUM(s.sales_amount) AS total_revenue,
		DENSE_RANK() OVER(ORDER BY SUM(s.sales_amount) DESC) AS rnk
	FROM gold.dim_products p
	JOIN gold.fact_sales s
	ON p.product_key = s.product_key
	GROUP BY p.product_name
)t 
WHERE rnk <= 5;

-- What are the 5 worst-performing products in terms of sales?
SELECT 
	product_name,
	total_revenue
FROM (
	SELECT 
		p.product_name,
		SUM(s.sales_amount) AS total_revenue,
		DENSE_RANK() OVER(ORDER BY SUM(s.sales_amount) ASC) AS rnk
	FROM gold.dim_products p
	JOIN gold.fact_sales s
	ON p.product_key = s.product_key
	GROUP BY p.product_name
)t 
WHERE rnk <= 5;

-- Find the Top-10 customers who have generated the highest revenue 
SELECT
	customer_key,
	first_name,
	last_name,
	total_revenue
FROM (
	SELECT
		c.customer_key,
		c.first_name,
		c.last_name,
		SUM(s.sales_amount) AS total_revenue,
		DENSE_RANK() OVER(ORDER BY SUM(s.sales_amount) DESC) AS rnk
	FROM gold.dim_customers c
	JOIN gold.fact_sales s
	ON c.customer_key = s.customer_key
	GROUP BY c.customer_key,
	c.first_name,
	c.last_name
)t
WHERE rnk <= 10;

-- 3 customers with the fewest orders placed.
-- Bottom 3 customers with the fewest orders (handles ties using DENSE_RANK)
SELECT
	customer_key,
	first_name,
	last_name,
	total_orders
FROM (
	SELECT
		c.customer_key,
		c.first_name,
		c.last_name,
		COUNT(DISTINCT s.order_number) AS total_orders,
		DENSE_RANK() OVER(ORDER BY COUNT(DISTINCT s.order_number) ASC) AS rnk
	FROM gold.dim_customers c
	JOIN gold.fact_sales s
	ON c.customer_key = s.customer_key
	GROUP BY c.customer_key,
	c.first_name,
	c.last_name
)t
WHERE rnk <= 3;


-- Bottom 3 customers by order count (TOP 3 without tie handling)
SELECT TOP 3
	c.customer_key,
	c.first_name,
	c.last_name,
	COUNT(DISTINCT s.order_number) AS total_orders
FROM gold.dim_customers c
JOIN gold.fact_sales s
ON c.customer_key = s.customer_key
GROUP BY c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders ASC
